#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
  --set=owner_password="$MIGRATION_DB_PASSWORD" --set=app_password="$APP_DB_PASSWORD" <<'SQL'
CREATE ROLE fhc_owner LOGIN PASSWORD :'owner_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE fhc_app LOGIN PASSWORD :'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO fhc_owner;
GRANT USAGE ON SCHEMA public TO fhc_app;
ALTER DEFAULT PRIVILEGES FOR ROLE fhc_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fhc_app;
ALTER DEFAULT PRIVILEGES FOR ROLE fhc_owner IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO fhc_app;
SQL
